// Caption cues are pure text+timing — they don't reference an Asset the way
// video/audio clips do (architecture doc v4.1 composition note). Generated by
// AI subtitle jobs; regenerating replaces the previous set for a project.
export interface CaptionCue {
  id: string;
  projectId: string;
  trackId: string;
  exportVersionId: string;
  text: string;
  startMs: number;
  endMs: number;
  orderIndex: number;
  createdAt: string;
}
