plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.vlogapp.videocomposer'
version = '0.1.0'

android {
  namespace "com.vlogapp.videocomposer"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.media3:media3-transformer:1.10.1"
}
